### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Damojan** [DiffusionLight/DiffusionLight#22]
i tried running this code :"""python inpaint.py --dataset C:\DiffusionLight\output\001\src\ --output_dir C:\DiffusionLight\output\001\output\""" in cmd and im getting this error """compiling unet model
Traceback (most recent call last):
  File "C:\DiffusionLight\inpaint.py", line 358, in <module>
    main()
  File "C:\DiffusionLight\inpaint.py", line 232, in main
    dataset = GeneralLoader(
  File "C:\DiffusionLight\relighting\dataset.py", line 87, in __init__
    self.scene_data = self._load_data_path(paths, num_samples=num_samples)
  File "C:\DiffusionLight\relighting\dataset.py", line 105, in _load_data_path
    if os.path.exists(os.path.splitext(paths[0])[0] + ".json") or os.path.exists(os.path.splitext(paths[-1])[0] + ".json"):
IndexError: list index out of range"""

**Comment by pureexe** [comment]
So, you solved the problem by putting image inside the src folder. is that correct?

**Comment by Damojan** [comment]
yeah simple solution, i'm not a coder so i don't know what i'm doing, my apologies.
