### ISSUE TITLE
Env problem

### ISSUE THREAD

**Issue by YacratesWyh** [DiffusionLight/DiffusionLight#26]
why you require openexr 3.2.1 in env.yml, and 1.3.9 in req.txt.
And you need matplotlib easydict opencv-python tensorboardx , to help using alphapose from a neet env.

Also I had a problem of
Traceback (most recent call last):
  File "/home/admin188/AI/DiffusionLight/inpaint.py", line 358, in <module>
    main()
  File "/home/admin188/AI/DiffusionLight/inpaint.py", line 340, in main
    output_image = pipe.inpaint_iterative(**kwargs)
  File "/home/admin188/AI/DiffusionLight/relighting/inpainter.py", line 328, in inpaint_iterative
    ball_images = generate_balls(
  File "/home/admin188/AI/DiffusionLight/relighting/inpainter.py", line 281, in generate_balls
    output_image = self.pipeline(
  File "/home/admin188/anaconda3/envs/fooocus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/admin188/AI/DiffusionLight/relighting/pipeline_xl.py", line 307, in __call__
    add_time_ids, add_neg_time_ids = self._get_add_time_ids(
  File "/home/admin188/anaconda3/envs/fooocus/lib/python3.10/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint_sd_xl.py", line 959, in _get_add_time_ids
    self.unet.config.addition_time_embed_dim * len(add_time_ids) + text_encoder_projection_dim
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

I have no idea why and I reinstalled from start and fixed it.

**Comment by pureexe** [comment]
I just realized that requirements.txt is set OpenEXR to 1.3.9, so I will update it to 3.2.1.

About the error, Are you able to run the example in the example folder?
```
python inpaint.py --dataset example --output_dir output
```

**Comment by YacratesWyh** [comment]
yes the error comes from running this and env problem is fine. I solved this by reinstalled env. I just want to make sure there's not any problem with plus an int and a NoneType.

**Comment by ScuLancer** [comment]
I have encountered the same problem, but reinstalling the environment cannot solve it. It seems to be a problem with diffusers. I don't know what your diffusers' _get_add_time_ids are like?[https://github.com/DiffusionLight/DiffusionLight/issues/42](url)
