### ISSUE TITLE
HuggingFace error

### ISSUE THREAD

**Issue by figo2264** [DiffusionLight/DiffusionLight#34]
My test environment is as below.
Ubuntu 24.04
Nvidia GPU (Coda toolkit and openexr is installed)
Python 3.9.21
Use pipenv instead of conda.

Somehow when I run the initial command as below.
```
 python inpaint.py --dataset model --output_dir output
```
It failed with the below message.

```
Traceback (most recent call last):
  File "/home/tempest/Projects/DiffusionLight/inpaint.py", line 15, in <module>
    from relighting.inpainter import BallInpainter
  File "/home/tempest/Projects/DiffusionLight/relighting/inpainter.py", line 2, in <module>
    from diffusers import ControlNetModel, AutoencoderKL
  File "/home/tempest/Projects/DiffusionLight/.venv/lib/python3.9/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/home/tempest/Projects/DiffusionLight/.venv/lib/python3.9/site-packages/diffusers/utils/__init__.py", line 36, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/home/tempest/Projects/DiffusionLight/.venv/lib/python3.9/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/home/tempest/Projects/DiffusionLight/.venv/lib/python3.9/site-packages/huggingface_hub/__init__.py)
```
Is there anything I missed?

**Comment by pureexe** [comment]
DiffusionLight is not compatible with newer version of huggingface-hub please downgrade it. I think 0.19.4 should be good

```
pip install huggingface-hub==0.19.4
```

**Comment by figo2264** [comment]
@pureexe Thanks. It works.
